### ISSUE TITLE
Add workflow to auto close stale issues

### ISSUE THREAD

**Issue by K20shores** [NCAR/micm-kpp#17]
We need to keep our issue count low if we can.

**Acceptance criteria**
- A workflow is added which auto closes issues that haven't been touched in some time

**Ideas**
- Replicate the workflow we already have in [micm](https://github.com/NCAR/micm/pull/729)

```
name: 'Close stale issues'
on:
  schedule:
    # Run every day at 7PM UTC
    - cron: '0 19 * * *'
jobs:
  close-stale:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 14 days with no activity.'
          days-before-stale: 180 # Mark as stale after 180 days of inactivity
          days-before-close: 14  # Close issue if no activity after 14 days of being stale
          days-before-pr-close: -1
          # Issues with this label are exempt from being checked if they are stale...
          exempt-issue-labels: Low Priority
          # Below are currently defaults, but given in case we decide to change
          operations-per-run: 30           # This setting specifies the maximum number of operations (such as marking issues as stale or closing them) that the action will perform in a single run
          stale-issue-label: Stale         # This setting defines the label that will be applied to issues that are considered stale
          close-issue-reason: not_planned  # This setting specifies the reason that will be given when closing stale issues

```
